// Automatically Generated by WIN32GUI Resource Splitter v1.1.5
// See latest details at http://www.torjo.com/win32gui/
//
// DONOT modify this manually. Changes will be overwritten automatically

#ifndef WIN32GUI_RES_icon_HPP
#define WIN32GUI_RES_icon_HPP

// in case you want to have a header be included first...
// Useful when you have shared resource IDs (IDs you can use throughout multiple projects)
//
// Also, you might need this in case you use standard IDs like IDOK, IDCANCEL, etc.
// Note: the same can be achieved with a precompiled header-file.
#ifdef WIN32GUI_RES_INCLUDE_ALWAYS
#include WIN32GUI_RES_INCLUDE_ALWAYS
#endif


namespace win32 { namespace gui { namespace res_id {

namespace icon_ {

}


}}}

#endif

