// Automatically Generated by WIN32GUI Resource Splitter v1.1.5
// See latest details at http://www.torjo.com/win32gui/
//
// DONOT modify this manually. Changes will be overwritten automatically

#ifndef WIN32GUI_RES_MENU_HPP
#define WIN32GUI_RES_MENU_HPP

namespace win32 { namespace gui { namespace res_id {

namespace menu_ {
  enum { file_exit = 40002 };
  enum { file_load = 40001 };
  enum { menu = 102 }; // menu group 


// these are the menus you can create/manipulate in you app.
// That is, you can say:
// menu m(menu_::group::main);
namespace group {
  enum { menu = 102 };

}
}


}}}

#endif

